"""Apply approved CR01 to active prose only; preserve historical execution code."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,shutil
root=Path(__file__).resolve().parents[1];out=root/'reports/p02c';changed=[]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(n):return (root/n).read_text(encoding='utf-8')
def write(n,s):
    p=root/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding='utf-8',newline='\n');changed.append(n)
def replace(n,old,new):
    s=read(n);assert s.count(old)==1,(n,old);write(n,s.replace(old,new))
approval='docs/TaskCognition_CR01_APPROVED.md';amendment='docs/amendments/CR01_2026-10-05_v1.md';now=datetime.now(timezone.utc).isoformat()
draft='docs/TaskCognition_CR01_feasibility_DRAFT.md';review='docs/P02B_coordinator_review.md'
authority={n:sha(root/n) for n in (approval,draft,review,'docs/prompts/P02C_adopt_CR01_prompt.md')}
write('reports/p02c/authority_supplement.json',json.dumps(dict(evidence_kind='development_observation',operation='offline_authority_read',timestamp_utc=now,files=authority,explanation='Draft and coordinator review became available at user-supplied paths after initial inventory/acceptance. Both now read. Event 012 and its acceptance record remain unchanged; no duplicate acceptance.'),indent=2)+'\n')
shutil.copyfile(root/approval,root/'reports/p02c/CR01_approval_source.md')
write(amendment,f'''# TaskCognition CR01, adopted specification v1

Specification ID: **TaskCognition-CR01-2026-10-05-v1**. Status: **approved amendment adopted; study not frozen**.

User approval date: **2026-10-05**, America/Chicago. Verbatim approval: **“Understood. I approve it”**.
Actual adoption timestamp (UTC): **{now}**. Approval and adoption are distinct events.
Approved source: `{approval}`, SHA-256 `{authority[approval]}`. The historical draft `{draft}` (SHA-256 `{authority[draft]}`) and review `{review}` (SHA-256 `{authority[review]}`) retain their earlier pending-decision wording as history, superseded only by the approved record.

## Authority and precise delta

The immutable original reference `reference/TaskCognition_Revised_Verified.pdf`, SHA-256 `9eed0fe74f46c3acbc200183cf11693f1bec66a1180568087aeb775c97d8f6c8`, governs except for this approved delta and previously accepted C01-C03 clarifications. This amendment supersedes its Section 5 and Figure 1 cap-selection branch: **both primary D and R use 2,048 total generated tokens, including thinking and final output. Completion is descriptive, with no 99% eligibility prerequisite or automatic stop based on that threshold.** The synchronized active protocol operationalizes that version. Future accepted immutable study/candidate/deployment records will govern execution; none is created here.

Strict native-channel/FINAL/native-syntax/native-score behavior is unchanged. Retain valid partial credit and all recorded model failures; no valid retainable answer means the declared zero score. Missing/corrupt evidence and software incidents stop the affected operation, never become fabricated zeros. All four audit inequalities, positive direct-perfect denominator bound, common all-in budget, fallback and all three primary superiority contrasts remain required. Low completion is not an eligibility rejection; invalid evidence, unresolved required freeze fields, inadequate denominator bounds and unaffordable/uninformative designs still block their relevant stages.

## Unchanged package and interpretation

Keep Qwen3-8B revision `b968826d9c46dd6066d109eabc6255188de91218`, native D/R switches, BF16 Windows SDPA MATH, the P02B tokenizer, effective matched sampler, exact P02B common instruction and strict parser. Keep Reasoning Gym revision `21e6d2a9a581b3e11aafe711abfd37402f8482d5`, six native families/renderers and equal weighting. No prompt search, repair, alternate model, filtering or new comparator choice.

CR01 was informed by P02A/P02B DEVELOPMENT format/truncation failures, before final labels. The original route paused on development-feasibility concerns; it did not formally test and fail its cap rule. Historical 1,024 and 2,048 packages and scores retain their original identities. Differences between the revised bounded packages can reflect solving, formatting and truncation; they do not isolate reasoning ability. No gate or superiority result is established.

## Affected artifacts and limits

Active root instructions, protocol, decision register/ledger, roadmap, architecture, evidence guidance, source/navigation statements, future P02-P09 prompts and freeze/completion templates are synchronized. Exact changed paths/hashes are in `reports/p02c/changed_artifacts.json` and the source diff; the reference audit classifies retained historical occurrences. The active revision copy is `paper/cr01-2026-10-05-v1/taskcognition.tex`; the entire original `docs/iclr2027` snapshot remains unchanged and recoverable from `reports/p02c/pre_CR01_source_snapshot.zip`.

Existing executable cap checks belong to closed historical P01/P02A/P02B runners; no general completion-eligibility validator or production freeze implementation exists. They remain unchanged for original-version verification. The prospective CR01 design template fixes the cap and descriptive policy explicitly; it is not an executable authorization or a final manifest. A future runner/freeze validator must enforce that version and still fail closed on all required fields and integrity checks.

Dataset/final population settings, features, repeat/sample counts, timeout, scalar cost/support bounds, beta, margins and resources remain development/design decisions. P01 stays sealed; P02A/P02B are accepted checkpoints. Only offline P02C is active, real dispatch false, P02 incomplete/unsealed, P03 unstarted. No generation, model load, encoder forward, gate training, final label or upload is authorized by adoption.
''')
replace('AGENTS.md','The included revised PDF fixes the scientific scope; the markdown operationalizes it.','The original revised PDF plus approved `docs/amendments/CR01_2026-10-05_v1.md` and accepted C01-C03 fixes the scientific scope; the active markdown operationalizes it. Historical PDF/source bytes remain immutable; CR01 explicitly supersedes only the old cap-eligibility branch.')
replace('AGENTS.md','7. Frozen package cap: 1,024 if all 12 mode-by-family development cells meet 99% strict-valid-FINAL; otherwise 2,048 if all meet it; otherwise stop the confirmatory study as infeasible. Any bigger cap is separate development-only diagnostic work.','7. CR01 primary common D/R cap: 2,048 total generated tokens, including thinking and final output. Completion and failure subtypes are descriptive for all 12 cells; no 99% eligibility prerequisite or automatic completion-threshold stop. Strict parsing, failure retention, audit denominator adequacy and all other audit/test requirements remain unchanged. Historical packages retain their original cap/version; no larger-cap or extra live work is authorized.')
replace('docs/PROTOCOL_SOURCE_OF_TRUTH.md',read('docs/PROTOCOL_SOURCE_OF_TRUTH.md').splitlines()[2],'Status: active pre-freeze specification `TaskCognition-CR01-2026-10-05-v1`. Authority: original reference PDF plus [approved CR01 adoption](amendments/CR01_2026-10-05_v1.md) and accepted C01-C03. P02 remains incomplete/unsealed. The historical source is preserved; the active revision copy is `paper/cr01-2026-10-05-v1`.')
replace('docs/PROTOCOL_SOURCE_OF_TRUTH.md','- Shared terminal output cap selected in development: 1,024 if every mode-by-family strict-valid-FINAL rate is at least 99%; otherwise test 2,048 across all cells; if any cell still fails, stop. Cap covers all generated output tokens, including thinking and final output. Confirm this interpretation against the backend and log it before the cap study.','- CR01 fixes the common primary D/R cap at 2,048 total generated tokens, including thinking and final output. Report strict-valid-FINAL completion and failure subtypes in all 12 cells descriptively; no 99% eligibility prerequisite or automatic threshold stop. Keep the exact P02B instruction and effective matched sampler/parser. Historical 1,024 artifacts remain valid under their original identities, never reinterpreted as CR01.')
write('docs/PROTOCOL_SOURCE_OF_TRUTH.md',read('docs/PROTOCOL_SOURCE_OF_TRUTH.md')+'\n## CR01 development provenance\n\nP02A/P02B exposed formatting and truncation problems on DEVELOPMENT inputs. The user approved CR01 on 2026-10-05 before any final labels. This outcome-informed amendment concerns bounded answer packages, including compliance and truncation; it does not establish improved native solving or routing. The original rule was not formally rejected. Completion alone cannot reject CR01 eligibility; unresolved freeze fields, invalid scores/costs, inadequate audit denominator bounds and software/evidence incidents still block the relevant action.\n')
replace('docs/DECISIONS_AND_GAPS.md','No blocking clarification is needed to start P00. Unknown workstation and repository details can be discovered locally. Scientific/resource choices below must be resolved before the relevant irreversible evidence stage, not guessed now.','Active version: TaskCognition-CR01-2026-10-05-v1. CR01 is approved and adopted; its former scientific-choice block is resolved. P02 remains incomplete; the remaining resource/design choices below are not approved by CR01.')
replace('docs/DECISIONS_AND_GAPS.md','Before cap pilot; final lock P04','Before next prospective pilot; final lock P04')
replace('docs/DECISIONS_AND_GAPS.md','| D07 | Cap-study sample plan and denominator | Predeclare inputs/repeats per cell and count failed requests conservatively in strict-valid-FINAL rates. Same evaluation rule at 1,024 and 2,048; no pooling cells to hide failure | Before cap run in P02 |','| D07 | CR01 primary cap resolved; descriptive completion design outstanding | Fixed 2,048 total D/R tokens; no completion eligibility threshold. Predeclare fresh inputs/repeats and planned/executed/retained denominators in all 12 cells; preserve failures and distinguish completion from correctness | Cap adopted 2026-10-05; sampling before next approved P02 run |')
replace('docs/DECISIONS_AND_GAPS.md','### Cap feasibility','### Fixed bounded packages under CR01')
replace('docs/DECISIONS_AND_GAPS.md',"The paper's small cap and 99% cellwise completion rule may make the planned package infeasible. A final output is not the same as a correct output. Freeze the completion definition before the pilot; do not weaken wrappers, omit failed rows, or simplify generators after observing failures to claim the original design passed. Legitimate development revisions are versioned and re-evaluated; the cap limit itself cannot be raised within the current confirmatory protocol.",'CR01 fixes 2,048 total tokens and removes completion-based eligibility and its automatic stop. Completion remains descriptive; wrong, partial and recorded failure scores remain in the distribution. No wrapper weakening, failed-row omission or easier-case selection is allowed. Low direct-perfect mass can still prevent denominator adequacy, and cost/design constraints can still make an informative study infeasible. The original route paused without a formal cap test. See `amendments/CR01_2026-10-05_v1.md`.')
replace('docs/IMPLEMENTATION_ROADMAP.md','12-cell completion report, cap decision, high-repeat estimates, workload estimate | Cap feasible and measurements trustworthy','12-cell descriptive completion at fixed 2,048 cap, repeat estimates, workload estimate | Measurements trustworthy; remaining feature/cost/design requirements reviewed')
replace('docs/IMPLEMENTATION_ROADMAP.md','- P02 cap failure at 2,048: confirmatory route stops. Preserve the evidence and prepare a feasibility report; do not start final data collection.','- P02 under CR01: low completion at the fixed 2,048 cap is reported, not an automatic eligibility stop. Integrity failures, unresolved required contracts and resource exhaustion still stop the affected work. Final labels await P03 design review and P04 freeze.')
write('docs/STATISTICAL_CONTRACT.md',read('docs/STATISTICAL_CONTRACT.md')+'\n## CR01 scope annotation (approved 2026-10-05)\n\nThe original PDF plus `amendments/CR01_2026-10-05_v1.md` governs. The primary cap is fixed at 2,048 total D/R output tokens; completion is descriptive, without the removed eligibility threshold. Every estimator, range, four-check audit inequality, positive b_min denominator requirement and three-contrast success criterion above is unchanged. Formatting/truncation failures remain in the score distribution. A low harm estimate with inadequate direct-perfect exposure cannot establish safety. No numerical tolerance, margin or design count is adopted here.\n')
write('docs/ARCHITECTURE_AND_DATA.md',read('docs/ARCHITECTURE_AND_DATA.md')+'\n## Versioned CR01 scope\n\nProspective primary contracts must identify `TaskCognition-CR01-2026-10-05-v1`, reference the approved amendment hash, use 2,048 total tokens for each D/R package and `completion_policy: descriptive`. See `configs/cr01_development_design_template.json`. This is an incomplete development template, not a study/candidate/deployment freeze. Any future production validator must reject other prospective primary caps and unresolved required freeze fields, while accepting no completion-threshold eligibility rejection.\n\nHistorical P01/P02A/P02B runners, immutable plans, schemas and fixtures retain their original versions/caps and remain closed. They cannot be reused to authorize CR01 dispatch. The existing StudyManifest is UNFROZEN-only and final collection always rejects; no full freeze validator is claimed. Score/cost ranges, exact perfect-score equality, denominator adequacy, no replay and evidence-integrity requirements remain unchanged.\n')
replace('docs/EVIDENCE_AND_MANUSCRIPT.md','- `INFEASIBLE`: prescribed bounded package or informative design cannot meet feasibility requirements within declared resources.','- `INFEASIBLE`: an informative valid design cannot meet its remaining cost, denominator or resource requirements. Under CR01, low completion alone is not this decision; the removed 99% prerequisite cannot trigger it.')
write('docs/EVIDENCE_AND_MANUSCRIPT.md',read('docs/EVIDENCE_AND_MANUSCRIPT.md')+'\n## CR01 manuscript and evidence authority\n\nThe active revision source is `paper/cr01-2026-10-05-v1/taskcognition.tex`, governed by the original PDF plus `docs/amendments/CR01_2026-10-05_v1.md` and C01-C03. The original `docs/iclr2027` package remains historical and immutable. Include the outcome-informed P02A/P02B development history, fixed 2,048-token package and descriptive completion; preserve all primary scores. Package differences include format compliance/truncation and do not isolate improved native solving. Keep final gate/audit/test result cells empty until those stages occur. Historical totals remain 75 admitted generations / 40,555 output tokens, including P01\'s separately labelled deliberate interruption.\n')
replace('docs/prompts/P02_development_pilot.md','# P02 prompt: six-family development feasibility','# P02 prompt: six-family development under approved CR01')
replace('docs/prompts/P02_development_pilot.md','cap-study sample plan BEFORE the cap outcomes','prospective repeated-draw sample plan BEFORE its outcomes')
replace('docs/prompts/P02_development_pilot.md',read('docs/prompts/P02_development_pilot.md').splitlines()[8],'3. Use the fixed CR01 cap of 2,048 total generated tokens for D and R. Predeclare per-cell planned/executed/retained denominators; report strict-valid-FINAL completion descriptively. No 99% prerequisite or automatic threshold stop applies. Keep strict scoring and every failure; no pooling to hide failures, output repair or cap escalation.')
replace('docs/prompts/P02_development_pilot.md','4. If cap-feasible, collect the approved bounded high-repeat pilot;','4. Only under a separately approved run plan, collect the bounded repeated-draw pilot;')
replace('docs/prompts/P02_development_pilot.md','- A valid cap decision or explicit infeasibility stop; strict formatting not confused with correctness.','- Versioned fixed-2,048 package and descriptive completion; strict formatting not confused with correctness. No automatic completion-threshold stop.')
replace('docs/prompts/P02_development_pilot.md','If infeasible, preserve and report the stop; do not continue to a different study.','If remaining cost, integrity or design requirements block progress, preserve and report that concrete issue. Low completion alone does not invoke the removed eligibility stop.')
replace('docs/prompts/P03_design_validation.md','A cap-infeasible study cannot proceed through this prompt.','CR01 fixes the primary cap at 2,048; completion is descriptive and imposes no eligibility threshold. All remaining cost/support, denominator and design requirements still apply.')
replace('docs/prompts/P04_freeze_and_labels.md','Reconcile accepted decisions with the revised PDF and decision ledger.','Reconcile accepted decisions with the original PDF plus adopted CR01 and C01-C03. Bind the specification version and amendment hash; primary D/R output caps must each be 2,048 total tokens.')
replace('docs/prompts/P04_freeze_and_labels.md','Validate cap decision provenance, cost bounds','Validate CR01 approval/version and fixed-cap provenance (no completion certification), cost bounds')
for n in ['docs/IMPLEMENTATION_ROADMAP.md','docs/ARCHITECTURE_AND_DATA.md','docs/EVIDENCE_AND_MANUSCRIPT.md']+[p.relative_to(root).as_posix() for p in (root/'docs/prompts').glob('P0[2-9]_*.md')]:
    s=read(n);pos=s.index('\n')+1;write(n,s[:pos]+'\nActive authority: original reference PDF + approved `TaskCognition-CR01-2026-10-05-v1` + C01-C03. This document does not authorize a new phase or live run.\n'+s[pos:])
write('docs/templates/PHASE_COMPLETION_TEMPLATE.md',read('docs/templates/PHASE_COMPLETION_TEMPLATE.md')+'\n## Applicable specification version\n\nRecord original PDF hash, adopted amendment/version/hash, approval versus adoption dates, historical package identities, and changed active references. Under CR01, fixed 2,048-token completion is descriptive; never use an obsolete cap-certification branch as eligibility. Distinguish zero new model/GPU work from offline preparation. No final freeze is implied by phase review.\n')
replace('docs/SOURCE_REGISTER.md',"References checked 2026-09-28: Qwen's official card supports native thinking switches and recommends much longer output allowance than this manuscript's 1,024/2,048 cap. Therefore the cap completion study is substantive, not a presumed pass.","Historical reference check (2026-09-28): Qwen's documented output allowances were longer than the original manuscript caps. Under approved CR01 the prospective primary cap is fixed at 2,048 and completion is descriptive; no cap-certification study is required. This offline adoption did not recheck current upstream documentation.")
write('docs/SOURCE_REGISTER.md',read('docs/SOURCE_REGISTER.md')+'\n## Active authority after CR01\n\nOriginal PDF hash above remains unchanged. Approved `TaskCognition_CR01_APPROVED.md`, adopted `amendments/CR01_2026-10-05_v1.md`, and accepted C01-C03 supply the explicit limited revisions. `paper/cr01-2026-10-05-v1` is the active amended source copy; `docs/iclr2027` is historical. Consult `reports/p02c/reference_audit.md` rather than applying historical cap language to prospective CR01 work.\n')
replace('README.md','Prepared 2026-09-28. Status: implementation plan; no experiments or results.','Active specification: **TaskCognition-CR01-2026-10-05-v1**, approved 2026-10-05. P01 is sealed; P02A/P02B are accepted DEVELOPMENT checkpoints. P02C is offline adoption only; P02 remains incomplete/unsealed and live dispatch is disabled. There are no final gate/audit/test results.\n\nStart with [adopted CR01](docs/amendments/CR01_2026-10-05_v1.md), [active protocol](docs/PROTOCOL_SOURCE_OF_TRUTH.md), [active manuscript source](paper/cr01-2026-10-05-v1/taskcognition.tex), and [P02C report](reports/phases/P02C_completion.md). Primary D/R cap is fixed at 2,048 total tokens; completion is descriptive, with no eligibility threshold. Historical bootstrap instructions below are retained for provenance, not current authorization.')
replace('README.md','## Start here','## Historical initial handoff (2026-09-28)')
write('reports/decision_ledger.md',read('reports/decision_ledger.md')+f'''\n## P02C / CR01 adoption\n\nApproval date: **2026-10-05**, America/Chicago. Verbatim user approval: **“Understood. I approve it”**. Actual adoption UTC: **{now}**. Approved source SHA-256 `{authority[approval]}`. Adopted amendment `{amendment}`, SHA-256 `{sha(root/amendment)}`.\n\nP02B accepted once in event 012 after four-artifact/598-file verification; the later supplied coordinator review confirms it. P01 remains sealed and P02A/P02B accepted. CR01 resolves the scientific-choice pause only: fixed 2,048 primary D/R total tokens, descriptive completion, no 99% eligibility or automatic threshold stop. P02 remains incomplete/unsealed; P03 unstarted; real dispatch false.\n\nAffected artifacts: root AGENTS/README; active protocol, statistical scope annotation, decisions, roadmap, architecture/evidence/source guidance; future P02-P09 prompts; completion/freeze templates; versioned development design template; revised manuscript/figure in `paper/cr01-2026-10-05-v1`. Exact path/hash inventory: `reports/p02c/changed_artifacts.json`. Original sources and all diagnostic scores remain unchanged. C01-C03, method/comparators, audit inequalities and all primary superiority criteria continue to govern. D05/D06/D08-D17 remain unresolved where not already accepted; no final values or resource authority are inferred. No new generations or features were measured.\n''')
write('configs/cr01_development_design_template.json',json.dumps(dict(artifact_role='incomplete_development_design_template_not_manifest',specification_version='TaskCognition-CR01-2026-10-05-v1',original_pdf_sha256='9eed0fe74f46c3acbc200183cf11693f1bec66a1180568087aeb775c97d8f6c8',amendment_path=amendment,amendment_sha256=sha(root/amendment),approval_source_sha256=authority[approval],primary_output_cap_total_tokens={'D':2048,'R':2048},completion_policy='descriptive_no_eligibility_threshold',instruction_source='artifacts/development/p02b-two-cap/package_base.json',instruction_hash_encoding='SHA-256 of canonical JSON string, UTF-8; taskcognition.contracts.digest',instruction_text_utf8_sha256=hashlib.sha256(json.loads(read('reports/p02b/instruction_diff.json'))['new'].encode('utf-8')).hexdigest(),instruction_sha256=json.loads(read('reports/p02b/instruction_diff.json'))['new_sha256'],strict_scoring_unchanged=True,final_freeze=False,real_dispatch_enabled=False,unresolved=dict(dataset_final_configs=None,features=None,repeats=None,sample_sizes=None,timeout=None,scalar_cost=None,cost_support_bounds=None,beta=None,alpha=None,b_min=None,delta_score=None,resource_ceiling=None,backup_destination=None)),indent=2)+'\n')
event='configs/state_events/013_CR01_adopted_offline.json';statepath=root/'configs/phase_state.json';state=json.loads(statepath.read_text())
write(event,json.dumps(dict(evidence_kind='development_observation',timestamp_utc=now,event='CR01_adopted',approval_date='2026-10-05',approval_timezone='America/Chicago',approval_verbatim='Understood. I approve it',approved_source_sha256=authority[approval],adopted_amendment_sha256=sha(root/amendment),authority_files=authority,previous_state_sha256=sha(statepath),real_dispatch_enabled=False,p02_complete=False,p02_sealed=False),indent=2)+'\n')
state.update(latest_event=event,specification_version='TaskCognition-CR01-2026-10-05-v1',amendment_sha256=sha(root/amendment),real_dispatch_enabled=False)
write('configs/phase_state.json',json.dumps(state,sort_keys=True,separators=(',',':'))+'\n')
write('reports/p02c/active_edit_paths.json',json.dumps(sorted(set(changed)),indent=2)+'\n')
print('Adopted CR01 and synchronized active documents; historical runners and manuscript untouched.')
